image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - init: npm install
    command: npm run start

  - name: Start web server
    init: python -m http.server 3000